spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/tradingclient
    username: postgres
    password: ${TRADINGCLIENT_DB_PWD}
  flyway:
    locations:
    - db/migration/postgresql
    - db/data
