set schema 'dbo';

create table if not exists dbo.symbols (
    id                  smallint generated by default as identity primary key,
    questradeid         integer not null,
    symbol_name         varchar(10) not null,
    listing_exchange    varchar(20) null,
    constraint uniq_questradeid unique(questradeid)
);
